#!/bin/bash
#***************************************************************************
#*  Radiolina, un script bash dependiente de Mplayer para escuchar radios  *
#*  http://code.google.com/p/radiolina/                                    *
#*                                                                         *
#*  Copyright (c) 2008-2011                                                *
#*  Martín Gaitán - gaitan (at) gmail.com                                  *
#*                                                                         *
#* This program is free software: you can redistribute it and/or modify    *
#* it under the terms of the GNU General Public License as published by    *
#* the Free Software Foundation, either version 3 of the License, or       *
#* (at your option) any later version.                                     *
#*                                                                         *
#* This program is distributed in the hope that it will be useful,         *
#* but WITHOUT ANY WARRANTY; without even the implied warranty of          *
#* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the           *
#* GNU General Public License for more details.                            *
#*                                                                         *
#* You should have received a copy of the GNU General Public License       *
#* along with this program.  If not, see <http://www.gnu.org/licenses/>.   *
#***************************************************************************


echo "Radiolina v0.4  Copyright (C) 2011 Martín Gaitán"
echo "Este programa se ofrece SIN GARANTÍA ALGUNA;"
echo "Es software libre, y usted puede redistribuirlo bajo ciertas condiciones;"
echo "Vea <http://www.gnu.org/licenses/gpl-3.0.html> para más detalles."
echo ""

case $1 in
    canal7)
    mplayer mms://canal7envivo.telecomdatacenter.com.ar/canal7envivo
    ;;

    tn|todomentiras)
    mplayer mms://streamtn.uigc.net/TN
    ;;


    dolina)
    mplayer http://venganzasdelpasado.com.ar/`date +%Y -d 'yesterday'`/lavenganza_`date +%Y-%m-%d -d 'yesterday'`.mp3
    ;;
    calf)
    mplayer  http://64.191.116.84:8030/
    ;;
    0|continental)
    mplayer rtmp://wmf03.host.mia.us.cadenaunionradio.com/arcontinental/arcontinental.stream
    ;;
    1|mitre)
    mplayer http://crp02.cienradios.com.ar/mitre790.mp3
    ;;
    2|rp)
    mplayer http://streaming.fmrockandpop.com/rockandpop?MSWMExt=.asf
    ;;
    3|ciudad)
    mplayer mms://streaming.netizen.com.ar/oncediez
    ;;
    4|delplata)
    mplayer mms://delplata.telecomdatacenter.com.ar/delplata
    ;;
    5|latribu)
    mplayer http://193.41.7.38:8820/
    ;;
    6|radio10)
    mplayer mms://200.43.193.143/radio10
    ;;
    7|la100)
    mplayer rtsp://g2.prima.com.ar/vivo/cadena100.rm
    ;;
    8|lared)
    mplayer rtmp://vivolared.multimediosamerica.com.ar/streamlared/&streamId=lared
    ;;
    9|eter)
    mplayer http://box01.sonic.fm:7172
    ;;
    10|metro)
    mplayer "rtmp://edgeamericaspushlivefs.fplive.net/edgeamericaspushlive-live/streamMetroRadio live=1" -vo null -cache 5000 -cache-min 50
    ;;
    11|mega)
    mplayer http://mega.telecomdatacenter.com.ar/mega
    ;;
    12|40principales)
    mplayer http://66.175.96.10/ARLOS40P
    ;;
    13|cool)
    mplayer mms://67.19.12.42/coolradio
    ;;
    14|nacional)
    mplayer http://208.85.241.150:8010/
    ;;
    15|rnma)
    mplayer http://lilith.nodo50.org:8000/mediosalter.mp3
    ;;
    16|belgrano)
    mplayer mms://a1585.l2573453584.c25734.g.lm.akamaistream.net/D/1585/25734/v0001/reflector:53584
    ;;
    17|nacionalrock)
    mplayer http://208.85.241.150:8162/
    ;;
    18|madres)
    mplayer http://200.68.81.65:8000/am530
    ;;
    19|unc)
    mplayer mms://wms1.barracas.sinectis.com.ar/am580
    ;;
    *|-help)

    echo "uso: ./radiolina <numero de la radio>"
    echo ""
    echo "RADIOS DISPONIBLES"
    echo ""
    echo canal7
    echo dolina
    echo calf
    echo 0. Continental
    echo 1. Radio Mitre
    echo 2. Rock And pop
    echo 3. Radio de la Ciudad
    echo 4. Del plata
    echo 5. La tribu
    echo 6. Radio 10
    echo 7. La 100
    echo 8. La Red
    echo 9. Eter
    echo 10. Metro
    echo 11. Mega
    echo 12. Los 40 principales
    echo 13. Cool Radio
    echo 14. Radio Nacional
    echo 15. Red Nacional de Medios Alternativos
    echo 16. Radio Belgrano
    echo 17. Nacional Rock 93.7
    echo 18. Radio Madres
    echo 19. Universidad Córdoba
    ;;


esac
